on: 
  push:
     branches:
        - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftpupload.net
        username: if0_36301216
        password: k9yw7XD3MuuxGzm
        server-dir: /home/vol13_8/infinityfree.com/if0_36301216/
